export const salaryInfoContent = {
  basicSalary: "Basic Salary",
  bonus1: "Bonus 1",
  bonus2: "Bonus 2",
  bonusType: "Bonus Type",
  consultancyFess: "Consultancy Fees",
  empSIC: "Employee State Insurance Corporation",
  fullFinalPay: "Full & Final Payment",
  gratuity: "Gratuity",
  houseRentAllowance: "House Rent Allowance",
  incentives: "Incentives",
  incomeTax: "Income Tax",
  leaveDeduction: "Leave Deduction",
  medicalAllowance: "Medical Allowance",
  providentFund: "Provident Fund",
  proTax: "Professional Tax",
  specialAllowance: "Special Allowance",
  taxAtSource: "Tax Deduction At Source",
  fees: "Fees",
  tdsDeduction: "TDS Deduction (%)",
};
